import Link from 'next/link';

const modes = [
  ['Build', 'Chat, preview, inspector e task dock per il lavoro quotidiano.'],
  ['Focus Preview', 'Nasconde i pannelli e dedica lo spazio al prodotto.'],
  ['Visual Edit', 'Attiva il bridge nella preview, ispeziona un selector, apre il file mappato e applica patch con recovery point.'],
  ['Debug', 'Apre Quality e Console con eventi reali del Control Plane.'],
  ['Compare', 'Affianca la preview corrente all’ultima baseline evidence disponibile.'],
  ['Mobile Studio', 'Passa al viewport mobile grande e mantiene l’Inspector raggiungibile.'],
];

export default function Documentation() {
  return <main className="docs-shell"><header><div className="brand-mark">F</div><div><span className="eyebrow">FENIX / DOCUMENTAZIONE</span><h1>Dal brief a un’app funzionante.</h1><p>Guida operativa e confini verificati della beta web.</p></div><Link className="button secondary" href="/">Torna a FENIX</Link></header><section><h2>Cosa costruisce oggi</h2><p>Un nuovo progetto web viene analizzato dal Product Architect, pianificato dal Software Architect e costruito da agenti frontend, backend e dati. Il risultato contiene interfaccia specifica per il dominio, API autenticate, ruoli, SQLite, CRUD, ricerca, metriche, dati iniziali, test e preview isolata. I run degli agenti e le prove vengono salvati nel progetto.</p><p><strong>Confine della beta:</strong> GitHub OAuth, deploy su provider esterno, domini, app Expo native, pagamenti e MCP remoto richiedono ancora una connessione o un builder dedicato e non vengono dichiarati completati automaticamente.</p></section><section><h2>Flusso di creazione</h2><ol><li>Descrivi il prodotto e scegli <strong>Crea e costruisci</strong>.</li><li>FENIX genera e valida un Product Brief strutturato.</li><li>Gli agenti producono codice full-stack in un sandbox isolato.</li><li>Il QA esegue controlli statici, login, database, lettura, creazione, HTTP, visuale e accessibilità.</li><li>Solo dopo i gate viene resa disponibile la preview verificata e uno snapshot recuperabile.</li></ol></section><section><h2>Flusso Visual Edit</h2><ol><li>Apri un progetto con preview live e scegli <strong>Visual Edit</strong>.</li><li>Clicca un elemento nella preview oppure inserisci un selector CSS.</li><li>Conferma <strong>Ispeziona elemento</strong>: FENIX salva screenshot, mapping e scope.</li><li>Se il source mapping è valido, modifica il file nel patch editor.</li><li>Applica la patch. Ogni modifica idonea crea una recovery point persistente.</li><li>Usa <strong>Undo</strong> per ripristinare file e repository index.</li></ol></section><section><h2>Modalità</h2><div className="docs-grid">{modes.map(([title,text])=><article key={title}><strong>{title}</strong><p>{text}</p></article>)}</div></section><section><h2>Gate di sicurezza</h2><p>Freeze, file protetti, precondizioni hash, autenticazione, autorizzazione, quality evidence, approvazioni e rollback sono applicati dal server. Un pulsante non può aggirare queste policy.</p></section></main>;
}
